apiVersion: v2
name: template-controller
maintainers:
  - name: kluctl
    url: https://github.com/kluctl/charts
  - email: aljoscha.poertner@posteo.de
    name: AljoschaP
  - email: ablock84@gmail.com
    name: codablock
description: A Helm chart for the template-controller
type: application
version: 0.2.1
appVersion: "v0.6.0"
